Rock Paper Scissors, the game!
- appid: 224658110883993
- d37dfe315494b6959a59a8571c7a8f51

* App Requests
- http://apps.facebook.com/superfbrps/?request_ids=10150325900554428&ref=notif&notif_t=app_request

* Notes
** og doesn't re-grab objects. this is a pain.

* Settings:
** alskdjfjfhg : page path
Use Case:
* Invite Facebook friend to rock-paper-scissors game
* 

* Developer Notes
** App Creation
- when creating an app the first time, the form you fill out doesn't lead you to the settings page, you have to go back to dashbaord and then edit.
- lot of fields I have no clue about
- finding a name for an app really sucks right now.
** Open Graph Updates

I've spent about a week now pretending to be a Facebook developer, and my overall impression is really positive barring a few cases below:

*** Creation and Caching of Nodes is Confusing.

- I can't update an achievement once I've created it (as far as I can tell).
- If I create an achievement and it has an error in, say, the og.url metadata, the object still gets created, so if I make it wrong it is wrong forever.

What this meant for me was that, when I screwed up an achievement somehow, I had to rename the url and a corresponding file every time (that's why the current achievements are e.g. 'winwithrock3'. 

I'd prefer an explicit interface for creation and editing of nodes separate from granting them (similar to the actions and object types workflow right now)

*** Misleading Error Messages

There were two dumb mistakes made that were made more difficult to debug by vague error messages:
- I had a typo in the og:url metadata. I could see the URL in the error message containing the og:url metadata getting hit, and the URL linter was able to parse the endpoint properly, but the error message was "type must be 'games.achievement', actually is ''". If it had said 'og:url param http://foo unreachable' it would have been clearer.
- I'd passed my access token and another argument concatenated together. The error code told me it was a stale access token instead of an invalid one. It'd be great to have it say 'access token should be this many characters etc.', but just saying 'invalid access token' would have gotten me to the problem more quickly.

*** Can't Run Test servers

It would be great if I could make calls to connect to the og using
servers other than the one specified in the developer settings (even
the domain restriction is limiting).

Perhaps a github model where dev servers could register public keys for an app.

*** The Node creation 'callback' behavior is confusing.

When I want to create and achievement, or have open graph objects, I have to make them accessible on my web server for Facebook servers to come and get the information. 

My preference would be to pass all the information along with the call itself, like a function call. 


*** More minor notes:
**** Using the app name for graph updates seems like a bad idea
the app id doesn't change, but I might change the app name. using <gamename>:<action name> 
**** I'd prefer not to have to use a facebook web page to create Nodes
The tools/opengraph editors are great, but we should provide explicit
Node management calls so this can be done programmatically. Most
developers will prefer to create and manage these within their own
application repositories. A game with dozens of actions, for example,
might have an edit and review workflow before publishing that they'll
want to track. As far as automation goes, the code that makes the
connections might be generated in the same step as the create/edit,
etc.

*** Summary
Barring the things above, the developer experience has been very smooth for me so far.
